inventory = new Meteor.Collection("Inventory");
companies = new Meteor.Collection("Companies");
hmos = new Meteor.Collection("HMOs");
services = new Meteor.Collection("Services");
service_processes = new Meteor.Collection("Service Processes");
processes = new Meteor.Collection("Processes");
process_items = new Meteor.Collection("Process Items");
pro_services = new Meteor.Collection("Professional Services");
patients = new Meteor.Collection("Patients");